version: '3.9'

x-aws-vpc: "vpc-0155daaba0a498f7d"

services:
  application:
    image: dimdasci/annotated-text-visualisation:latest
    ports:
      - target: 8501
        published: 8501
        protocol: tcp
        x-aws-protocol: http