version: '3.9'

services:
  application:
    image: dimdasci/annotated-text-visualisation:0.2.0
    ports:
      - target: 8501
        published: 8501
        protocol: tcp
        x-aws-protocol: http